### ISSUE TITLE
Still relevant?

### ISSUE THREAD

**Issue by b-ma** [padenot/webaudio-benchmark#4]
Hey Paul, hope to find you well

I was wondering if you still considered this repo as relevant ? 
I found a few of issues I think and I wondered if you would be interested in a PR (or not)

Cheers,
Benjamin

**Comment by padenot** [comment]
Yes, it's being run daily in CI to track browser regressions, please send patches, thanks!

**Comment by b-ma** [comment]
ok cool!

**Comment by padenot** [comment]
Closing now that #5 is merged. Thanks again!

**Comment by b-ma** [comment]
My pleasure!
